language: node_js
node_js:
  - "10"
  - "11"
jobs:
  include:
    - stage: Produce Coverage
      node_js: "11"
      script: npm install coveralls && npm run coverage && nyc report --reporter=text-lcov | coveralls